USE DATABASE PURAN_DB;

USE SCHEMA PURAN_SC;


-- ARN removed for security, set manually during execution


CREATE OR REPLACE STORAGE INTEGRATION S3_FLIGHT_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = $AWS_ROLE_ARN
STORAGE_ALLOWED_LOCATIONS = ('s3://saven-task/Flight_Data/Flight.csv');


DESC STORAGE INTEGRATION S3_FLIGHT_INT;

CREATE OR REPLACE FILE FORMAT PURAN_DB.PURAN_SC.CSV_HEADER_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
PARSE_HEADER = TRUE
SKIP_HEADER = 0;


CREATE OR REPLACE FILE FORMAT PURAN_DB.PURAN_SC.CSV_LOAD_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
PARSE_HEADER = FALSE
SKIP_HEADER = 1;


CREATE OR REPLACE STAGE PURAN_DB.PURAN_SC.FLIGHT_S3_EXT_STAGE
URL = 's3://saven-task/Flight_Data/Flight.csv'
STORAGE_INTEGRATION = S3_FLIGHT_INT;

LIST @FLIGHT_S3_EXT_STAGE;


SELECT *
FROM TABLE(
    INFER_SCHEMA(
        LOCATION=>'@PURAN_DB.PURAN_SC.FLIGHT_S3_EXT_STAGE',
        FILE_FORMAT=>'PURAN_DB.PURAN_SC.CSV_HEADER_FORMAT'
    )
);


CREATE OR REPLACE TABLE FLIGHT_T2
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
    FROM TABLE(
        INFER_SCHEMA(
            LOCATION=>'@PURAN_DB.PURAN_SC.FLIGHT_S3_EXT_STAGE',
            FILE_FORMAT=>'PURAN_DB.PURAN_SC.CSV_HEADER_FORMAT'
        )
    )
);

COPY INTO PURAN_DB.PURAN_SC.FLIGHT_T2
FROM @PURAN_DB.PURAN_SC.FLIGHT_S3_EXT_STAGE
FILE_FORMAT = (FORMAT_NAME = PURAN_DB.PURAN_SC.CSV_LOAD_FORMAT);


SELECT * FROM PURAN_DB.PURAN_SC.FLIGHT_T2;